version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
            
  lint-backend:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd backend
      - run: npm i
      - run: npm lint
      
  lint-frontend:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd frontend
      - run: npm i
      - run: npm lint
  
  backend-tests:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd backend
      - run: npm i
      - run: npm run tests

workflows:
  default:
    jobs:
      - lint-backend
      - lint-frontend
