version: 2.1

jobs:
            
  build-backend:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd backend
      - run: npm i
      - run: npm run-script build
      
  build-frontend:
    requires:
      - build-backend
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd frontend
      - run: npm i
      - run: npm run-script build
  
  backend-tests:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd backend
      - run: npm i
      - run: npm run tests

workflows:
  default:
    jobs:
      - build-backend
      - build-frontend
