version: 2.1

jobs:
            
  build-backend:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run-script build
      
  build-frontend:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd frontend && npm i 
      - run: cd frontend && npm run-script build
  
  backend-tests:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: cd backend && npm run tests

workflows:
  default:
    jobs:
      - build-backend
      - build-frontend:
          requires:
            - build-backend
